# Generated by Django 5.1 on 2024-11-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_conteudo_autor_alter_curso_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarioconteudo',
            old_name='usuario',
            new_name='autor',
        ),
        migrations.AddField(
            model_name='comentarioconteudo',
            name='comentario',
            field=models.TextField(default=None),
        ),
    ]
